### ISSUE TITLE
mapeador/mapping

### ISSUE THREAD

**Issue by heliosroots** [jcmoraisjr/jcore#4]
Olá. Estou fazendo teste em seu OPF, esta ficando muito bom!!! Me parece que internamente ele usa a “RTTI” para fazer o mapeamento das classes e esse mapeamento é automático? Existe a possibilidade de não mapear determinado atributo  “published” de uma classe? 
Obrigado!!!

Hello.  I'm auditioning in your OPF, is getting very good !!! It seems to me that internally it uses the "RTTI" to map the classes and this mapping is automatic? There is a possibility to map certain attribute "published" in a class?
Thank you!!!

**Comment by jcmoraisjr** [comment]
I've just uploaded IsPersistent support on attribute metadata. Now you have two options: move the property to the public area and the metadata will be removed altogether, or update the JCore sources and change the IsPersistent state to False using the following syntax: VConfig.Model.AcquireAttrMetadata(TYourClass, 'YourPropertyName').IsPersistent := False;

Please reopen this issue if you have any problem.
