### ISSUE TITLE
[ws] Error: identifier idents no member "CompressedJSON"

### ISSUE THREAD

**Issue by mdbs99** [jcmoraisjr/jcore#6]
I can't compile the WS package using FPC 2.6.5.

Compile package JCoreWSRT 0.0: Exit code 1, Errors: 1
jcorewsjson.pas(104,15) Error: identifier idents no member "CompressedJSON"

**Comment by jcmoraisjr** [comment]
Thanks for point this out. Some ifdefs were created in order to compile sources on 2.6, however WS tests still requires FPC 3 because of JSON compression implementation.
