### ISSUE TITLE
questions...

### ISSUE THREAD

**Issue by heliosroots** [jcmoraisjr/jcore#8]
I have some questions...

1 - How to deal with the types of streams, blobs, etc.

2 - How to deal with a legacy DBMS fields where "ID" has a different type of nomenclature ...

Obrigado!!!

**Comment by jcmoraisjr** [comment]
There are still some missing features that I am currently working on. One of them is new data types such as streams, another one is some metadata for the OID. A few more days and you can see these changes in the repository. Stay tuned.
